import type { MetadataRoute } from 'next';

/**
 * Programmatic robots.txt — generated by Next.js App Router.
 * Update allow/disallow rules as new routes are added.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/_next/'],
      },
    ],
    sitemap: 'https://saloenza.com/sitemap.xml',
    host: 'https://saloenza.com',
  };
}
